Dev/appbase/src/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="home"),
    path('vehicle/', include('vehicle.urls', namespace='vehicle')),
]
if settings.DEBUG:
    urlpatterns += (static(settings.STATIC_URL,
                           document_root=settings.STATIC_ROOT))
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Dev/appbase/src/vehicle/urls.py
from django.urls import path
from . import views

app_name = 'vehicle'
urlpatterns = [
    path('', views.VehicleListView.as_view(), name='list'),
    path('create/', views.VehicleCreateView.as_view(), name='create'),
    path('video/', views.VideoConference.as_view(), name='video'),
    path('detail/<int:pk>/', views.VehicleDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.VehicleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.VehicleDeleteView.as_view(), name='delete'),
]

Dev/appbase/src/vehicle/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy

# Create your models here.


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    return 'vehicles/user_{0}_{1}/{2}'.format(instance.name, filename)


class Vehicle(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    model = models.IntegerField(default=0000)
    rate = models.CharField(max_length=100)
    body_number = models.CharField(max_length=100)
    engine_number = models.CharField(max_length=100)
    registration_number = models.CharField(max_length=50)
    color = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    images = models.FileField(upload_to=user_directory_path, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('vehicle:detail', kwargs={'pk': self.pk})

Dev/appbase/src/vehicle/forms.py
from django import forms
from .models import Vehicle


class VechicleModelForm(forms.ModelForm):
    name = forms.CharField(label='Vehicle Name:', widget=forms.TextInput(attrs={
        'placeholder': 'Vehicle name', 'class': 'form-control'
    }))
    model = forms.CharField(label='Model:', widget=forms.TextInput(attrs={
        'placeholder': 'Model of Vehicle', 'class': 'form-control'
    }))
    rate = forms.CharField(label='Price:', widget=forms.TextInput(attrs={
        'placeholder': 'Rate of Vehicle', 'class': 'form-control'
    }))
    body_number = forms.CharField(label='Body Number:', widget=forms.TextInput(attrs={
        'placeholder': 'Body number of Vehicle', 'class': 'form-control'
    }))
    engine_number = forms.CharField(label='Engine Number:', widget=forms.TextInput(attrs={
        'placeholder': 'Engine number of Vehicle', 'class': 'form-control'
    }))
    registration_number = forms.CharField(label='Registration Number:', widget=forms.TextInput(attrs={
        'placeholder': 'Registration number of Vehicle', 'class': 'form-control'
    }))
    description = forms.CharField(label='Description:', widget=forms.Textarea(attrs={
        'placeholder': 'Description', 'class': 'form-control'
    }))
    images = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        model = Vehicle
        fields = ['name', 'model', 'rate',
                  'body_number', 'engine_number', 'registration_number', 'description', 'images']

Dev/appbase/src/app/views.py
from django import views
from django.shortcuts import render


def index(request):
    return render(request, 'base.html')

Dev/appbase/src/vehicle/views.py
from app.settings import MEDIA_ROOT
from django.shortcuts import render
from django.views.generic import (
    CreateView, ListView, UpdateView, DeleteView, DetailView, TemplateView)
from . mixins import FormUserNeededMixin, UserOwnerMixin
from . forms import VechicleModelForm
from . models import Vehicle
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.forms import modelformset_factory

# Create your views here.


class VehicleCreateView(FormUserNeededMixin, CreateView):
    form_class = VechicleModelForm
    template_name = 'vehicle/vehicle_add.html'


class VehicleDetailView(UserOwnerMixin, DetailView):
    queryset = Vehicle.objects.all()


class VehicleListView(ListView):
    def get_queryset(self, *args, **kwargs):
        queryset = Vehicle.objects.filter(user=self.request.user)
        # print(self.request.GET)
        query = self.request.GET.get("q", None)
        if query is not None:
            queryset = queryset.filter(
                Q(content__icontains=query) | Q(user__username__icontains=query))
        return queryset


class VehicleUpdateView(LoginRequiredMixin, UserOwnerMixin, UpdateView):
    queryset = Vehicle.objects.all()
    form_class = VechicleModelForm
    template_name = 'vehicle/vehicle_edit.html'


class VehicleDeleteView(LoginRequiredMixin, UserOwnerMixin, DeleteView):
    model = Vehicle
    success_url = reverse_lazy("vehicle:list")


class VideoConference(TemplateView):
    template_name = 'vehicle/video-conference.html'

Dev/appbase/src/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VIMS - We care for you </title>
    {% include 'stylesheets.html' %}
</head>

<body>
    <div class="container-scroller">
        {% include 'navbar.html' %}
        <div class="container-fluid page-body-wrapper">
            <div class="main-panel">
                <div class="content-wrapper">
                    {% block body %}

                    {% endblock body %}
                </div>
            </div>
            {% include 'footer.html' %}
        </div>
    </div>
    {% include 'scripts.html' %}
</body>

</html>

Dev/appbase/src/templates/footer.html
<footer class="footer">
    <div class="w-100 clearfix">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block text-dark">
            <i class="fas fa-copyright float-left mr-2" style="font-size:18px;"></i> Copyright © 2018 <a href="/"
                target="_blank">VIMS</a>. All rights reserved.
        </span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center text-dark">
            <i class="fas fa-car-crash mr-2" style="font-size:20px;"></i> Vehicle Insurance Management
            System
        </span>
    </div>
</footer>

Dev/appbase/src/templates/navbar.html
<div class="horizontal-menu">
    <nav class="navbar top-navbar bg-dark col-lg-12 col-12 p-0">
        <div class="container">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo text-white" href="/">
                    <h1 style="font-family:Pacifico">Vims</h1>
                </a>
                <a class="navbar-brand brand-logo-mini" href="/">
                    <img src="../../images/logo-mini.svg" alt="logo" />
                </a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end justify-content-lg-start">
                <ul class="navbar-nav mr-lg-2">
                    <li class="nav-item nav-search d-none d-lg-block">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="search">
                                    <i class="mdi mdi-magnify"><i class="fas fa-search    "></i></i>
                                </span>
                            </div>
                            <input type="text" class="form-control" placeholder="search" aria-label="search"
                                aria-describedby="search">
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav navbar-nav-right">
                    <!-- @*<li class="nav-item dropdown">
                                <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#"
                                    data-toggle="dropdown">
                                    <i class="mdi mdi-bell-outline ml-2"><i class="fa fa-bell"
                                            aria-hidden="true"></i></i>
                                    <span class="count"></span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list"
                                    aria-labelledby="notificationDropdown">
                                    <a class="dropdown-item" style="cursor: pointer;">
                                        <p class="mb-0 font-weight-normal float-left">
                                            You have 4 new notifications
                                        </p>
                                        <span class="badge badge-pill badge-warning float-right">View all</span>
                                    </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item preview-item">
                                        <div class="preview-thumbnail">
                                            <div class="preview-icon bg-success">
                                                <i class="mdi mdi-information mx-0"></i>
                                            </div>
                                        </div>
                                        <div class="preview-item-content">
                                            <h6 class="preview-subject font-weight-medium">Application Error</h6>
                                            <p class="font-weight-light small-text mb-0">
                                                Just now
                                            </p>
                                        </div>
                                    </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item preview-item">
                                        <div class="preview-thumbnail">
                                            <div class="preview-icon bg-warning">
                                                <i class="mdi mdi-settings mx-0"></i>
                                            </div>
                                        </div>
                                        <div class="preview-item-content">
                                            <h6 class="preview-subject font-weight-medium">Settings</h6>
                                            <p class="font-weight-light small-text mb-0">
                                                Private message
                                            </p>
                                        </div>
                                    </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item preview-item">
                                        <div class="preview-thumbnail">
                                            <div class="preview-icon bg-info">
                                                <i class="mdi mdi-account-box mx-0"></i>
                                            </div>
                                        </div>
                                        <div class="preview-item-content">
                                            <h6 class="preview-subject font-weight-medium">New user registration</h6>
                                            <p class="font-weight-light small-text mb-0">
                                                2 days ago
                                            </p>
                                        </div>
                                    </a>
                                </div>
                            </li>*@ -->
                    <!-- @using Microsoft.AspNet.Identity
                            @if (Request.IsAuthenticated)
                            {
                            using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class
                            = "navbar-right" }))
                            {
                            @Html.AntiForgeryToken()
                            <li class="nav-item nav-profile dropdown">
                                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown"
                                    id="profileDropdown">
                                    <i class="fas fa-user-circle"
                                        style="font-size:30px;margin-left:-20px !important;"></i>
                                    <span class="nav-profile-name">Hello @User.Identity.GetUserName() ! &nbsp; <i
                                            class="fa fa-caret-down" aria-hidden="true"></i></span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right navbar-dropdown"
                                    aria-labelledby="profileDropdown">
                                    <a class="dropdown-item" href="/Manage/Index/">
                                        <i class="mdi mdi-settings text-dark"><i class="fa fa-cogs"
                                                aria-hidden="true"></i></i>
                                        Manage
                                    </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item"
                                        href="javascript:document.getElementById('logoutForm').submit()">
                                        <i class="mdi mdi-logout text-dark"><i class="fa fa-sign-out"
                                                aria-hidden="true"></i></i>
                                        Logout
                                    </a>


                                </div>
                            </li>
                            }
                            } -->
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
                    data-toggle="horizontal-menu-toggle">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </div>
    </nav>
    <nav class="bottom-navbar">
        <div class="container">
            <ul class="nav page-navigation">
                <li class="nav-item">
                    <a class="nav-link" href="/">
                        <i class="mdi mdi-view-dashboard-outline menu-icon"><i class="fa fa-home text-dark"
                                aria-hidden="true"></i></i>
                        <span class="menu-title">Home</span>
                    </a>
                </li>
                <!-- @if (User.IsInRole("Employee"))
                        {
                        <li class="nav-item">
                            <a class="nav-link" href="/Home/Dashboard">
                                <i class="mdi mdi-view-dashboard-outline menu-icon"><i class="fa fa-desktop text-dark"
                                        aria-hidden="true"></i></i>
                                <span class="menu-title">Dashboard</span>
                            </a>
                        </li>
                        } -->
                <li class="nav-item">
                    <a class="nav-link" href="/Manage/">
                        <i class="mdi mdi-view-dashboard-outline menu-icon"><i class="fa fa-user text-dark"
                                aria-hidden="true"></i></i>
                        <span class="menu-title">My Account</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="/PolicyTypes/" class="nav-link">
                        <i class="mdi mdi-image-filter menu-icon"><i class="fa fa-money text-dark"
                                aria-hidden="true"></i></i>
                        <span class="menu-title">Types of Insurance</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="/Home/Contact/" class="nav-link">
                        <i class="mdi mdi-image-filter menu-icon"><i class="fa fa-phone text-dark"
                                aria-hidden="true"></i></i>
                        <span class="menu-title">Contact US</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="/Home/About/" class="nav-link">
                        <i class="mdi mdi-file-document-box-outline menu-icon"><i class="fa fa-info text-dark"
                                aria-hidden="true"></i></i>
                        <span class="menu-title">About Us</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="/Home/SiteMap/" class="nav-link">
                        <i class="mdi mdi-file-document-box-outline menu-icon">
                            <i class="fa fa-map-marker text-dark" aria-hidden="true"></i>
                        </i>
                        <span class="menu-title">Site Map</span>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</div>

Dev/appbase/src/templates/scripts.html
{% load static %}
<script src="{% static 'static/js/jquery-3.4.1.js' %}"></script>
<script src="{% static 'static/js/4a55c4159e.js' %}"></script>
<script src="{% static 'static/css/vendors/js/vendor.bundle.base.js' %}"></script>
<script src="{% static 'static/css/vendors/js/vendor.bundle.addons.js' %}"></script>
<script src="{% static 'static/js/off-canvas.js' %}"></script>
<script src="{% static 'static/js/hoverable-collapse.js' %}"></script>
<script src="{% static 'static/js/template.js' %}"></script>
<script src="{% static 'static/js/settings.js' %}"></script>
<script src="{% static 'static/js/dashboard.js' %}"></script>
<script src="{% static 'static/js/todolist.js' %}"></script>
<script src="{% static 'static/js/jquery.datetimepicker.js' %}"></script>

Dev/appbase/src/templates/stylesheets.html
{% load static %}
<link rel="stylesheet" href="{% static 'static/css/horizontal-layout/style.css' %}">
<link rel="stylesheet" href="{% static 'static/css/vendors/css/vendor.bundle.base.css' %}">
<link rel="stylesheet" href="{% static 'static/css/vendors/css/vendor.bundle.addons.css' %}">
<link rel="stylesheet" href="{% static 'static/css/animate.css' %}">
<link rel="stylesheet" href="{% static 'static/css/jquery.datetimepicker.css' %}">
<link rel="stylesheet" href="{% static 'static/css/custom.css' %}">

Dev/appbase/src/vehicle/templates/vehicle/detail.html
<div class="card {{shadow}}">
    <div class="card-body">
        <div class="row">
            <div class="col-8">
                <h1 style="font-family:Pacifico">Vehicle Details</h1>
            </div>
            <div class="col-4">
                <div class="float-right">
                    <a href="{% url 'vehicle:update' pk=object.id %}" class="btn btn-dark text-white"><i
                            class="fas fa-edit text-white"></i></a>
                    <a href="{% url 'vehicle:delete' pk=object.id %}" class="btn btn-danger text-white"><i
                            class="fa fa-trash text-white" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>

        <hr />
        <div class="row">
            <div class="offset-1 col">
                <h1 style="font-family:Pacifico">
                    {{object.name}}
                </h1>
                <div style="font-family:'Century Gothic'">
                    <div class="row">
                        <div class="col">
                            <h4>
                                by {{object.user}}
                            </h4>
                        </div>
                    </div>
                    <hr />
                    <div class="row">
                        <div class="col">
                            <h6 class="font-weight-bold">Images:</h6>
                            <div class="row m-3">
                                <div class="m-2">
                                    {% if object.images %}
                                    <a class="title" href="">
                                        <img src="/media/{{object.images}}" class="img-thumbnail float-left"
                                            style="width:200px;height:120px;" />
                                    </a>
                                    {% else %}
                                    <p class="h5">No images !!</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr />
                    <h6 class="font-weight-bold ">Basic Details:</h6>
                    <div class="row">
                        <div class="col">
                            <h6>
                                Rate: $ {{object.rate}}
                            </h6>
                        </div>
                        <div class="col">
                            <h6>
                                Color: {{object.color}}
                            </h6>
                        </div>
                        <div class="col">
                            <h6>
                                Model: {{object.model}}
                            </h6>
                        </div>

                    </div>
                    <hr />
                    <h6 class="font-weight-bold">Complex Details:</h6>
                    <div class="row">
                        <div class="col">
                            <p>
                                Vehicle Number: {{object.registration_number}}
                            </p>
                        </div>
                        <div class="col">
                            <p>
                                Body Number: {{object.body_number}}
                            </p>
                        </div>
                        <div class="col">
                            <p>
                                Engine Number: {{object.engine_number}}
                            </p>
                        </div>
                    </div>
                    <hr />
                    <h6 class="font-weight-bold">Description:</h6>
                    <div class="row">
                        <div class="col">
                            <p>
                                {{object.description}}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-1"></div>
        </div>
        <hr />
    </div>
</div>

Dev/appbase/src/vehicle/templates/vehicle/form.html
{% load crispy_forms_tags %}
<form {% if form_id %} id='{{ form_id }}' {% endif %} action="{% if action_url %}{{ action_url }}{% endif %}"
    class="w-100" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{  form | crispy }}
    <input class="btn btn-dark btn-lg mt-3 w-100" type="submit" value="{{btn_title}}">
</form>

Dev/appbase/src/vehicle/templates/vehicle/screen-brodcast.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <title>Screen Sharing Demo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href="./css/bootstrap.min.css">
    <link rel="stylesheet" href="./css/getHTMLMediaElement.css">

</head>

<body>
    <div class="container-fluid">
        <div class="text-center p-4">
            <h1>
                Screen Brodcasting
            </h1>
        </div>
        <section class="text-center">
            <input type="text" id="room-id" value="abcdef" autocorrect=off autocapitalize=off size=20>
            <button id="open-room">Open Room</button>
            <button id="join-room">Join Room</button>
            <button id="open-or-join-room">Auto Open Or Join Room</button>

            <div id="videos-container" style="margin: 20px 0;"></div>

            <div id="room-urls" class="text-center p-3"
                style="display: none;background: #F1EDED;margin: 15px -10px;border: 1px solid rgb(189, 189, 189);border-left: 0;border-right: 0;">
            </div>
        </section>
    </div>

    <script src="./js/jquery-3.3.1.slim.min.js"></script>
    <script src="./js/bootstrap.min.js"></script>
    <script src="./js/RTCMultiConnection.js"></script>
    <script src="./js/socket.io.js"></script>
    <script src="./js/getHTMLMediaElement.js"></script>
    <script src="./js/brodcast-screen.js"></script>

    <footer>
        <small id="send-message"></small>
    </footer>

    <script src="./js/common.js"></script>
</body>

</html>

Dev/appbase/src/vehicle/templates/vehicle/vehicle_add.html
{% extends 'base.html' %}
{% block title %}
{{block.super}}Create Tweet
{% endblock title %}
{% block body %}
<div class="card shadow-lg">
    <div class="card-body">
        <div class="row">
            <div class="col-11 ml-5 mt-4">
                <h1 class="styled-font">Add new Vehicle</h1>
                <hr />
                {% include 'vehicle/form.html' with form=form btn_title='Add' %}
            </div>
        </div>
    </div>
</div>

{% endblock body %}

Dev/appbase/src/vehicle/templates/vehicle/vehicle_confirm_delete.html
{% extends 'base.html' %}
{% block title %}
{{block.super}}Create Tweet
{% endblock title %}
{% block body %}

<div class="card shadow-lg">
    <div class="card-body">
        <div class="row">
            <div class="col-8">
                <h1 class="styled-font">Removing Vehicle</h1>
            </div>
        </div>
        <hr />
        <div class="m-4">
            {% include 'vehicle/detail.html' with shadow='shadow' %}
        </div>
        <div class="p-1"></div>
        <hr />
        <form action="" method="POST">
            {% csrf_token %}
            <h1>Are you sure you want to delete this "{{object}}" ?</h1>
            <a href="{% url 'vehicle:list' %}">Go back to list</a> |
            <input type="submit" value="Confirm" class="btn btn-danger mt-2">
        </form>
    </div>
</div>
{% endblock body %}

Dev/appbase/src/vehicle/templates/vehicle/vehicle_detail.html
{% extends 'base.html' %}
{% block title %}
{{block.super}}Create Tweet
{% endblock title %}
{% block body %}
{% include 'vehicle/detail.html' with shadow='shadow-lg' %}
{% endblock body %}

Dev/appbase/src/vehicle/templates/vehicle/vehicle_edit.html
{% extends 'base.html' %}
{% block title %}
{{block.super}}Create Tweet
{% endblock title %}
{% block body %}
<div class="card shadow-lg">
    <div class="card-body">
        <div class="row">
            <div class="col-11 ml-5 mt-4">
                <h1 class="styled-font">Add new Vehicle</h1>
                <hr />
                {% include 'vehicle/form.html' with form=form btn_title='Update' %}
            </div>
        </div>
    </div>
</div>

{% endblock body %}

Dev/appbase/src/vehicle/templates/vehicle/vehicle_list.html
{% extends 'base.html' %}
{% block title %}
{{block.super}}Create Tweet
{% endblock title %}
{% block body %}
<div class="card shadow-lg">
    <div class="card-body">
        <h1 class="styled-font">Vehicles</h1>
        <hr>
        <table class="table table-hover table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Name</th>
                    <th>Model</th>
                    <th>Registration number</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for vehicle in object_list %}
                <tr>
                    <td>{{ vehicle.name }}</td>
                    <td>{{ vehicle.model }}</td>
                    <td>{{ vehicle.registration_number }}</td>
                    <td><a href="{% url 'vehicle:detail' pk=vehicle.id %}">View</a> | <a
                            href="{% url 'vehicle:update' pk=vehicle.id %}">Edit</a> | <a
                            href="{% url 'vehicle:delete' pk=vehicle.id %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}

            </tbody>

        </table>
    </div>
</div>

{% endblock body %}

Dev/appbase/src/vehicle/templates/vehicle/video-brodcast.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <title>Live Stream Demo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href="./css/bootstrap.min.css">
    <link rel="stylesheet" href="./css/getHTMLMediaElement.css">

</head>

<body>
    <div class="container-fluid">
        <div class="text-center p-4">
            <h1>
                Video Brodcasting
            </h1>
        </div>

        <section class="text-center">
            <input type="text" id="room-id" value="abcdef" autocorrect=off autocapitalize=off size=20>
            <button id="open-room">Open Room</button>
            <button id="join-room">Join Room</button>
            <button id="open-or-join-room">Auto Open Or Join Room</button>

            <div id="videos-container" style="margin: 20px 0;"></div>

            <div id="room-urls" class="text-center"
                style="display: none;background: #F1EDED;margin: 15px -10px;border: 1px solid rgb(189, 189, 189);border-left: 0;border-right: 0;">
            </div>
        </section>

    </div>

    <script src="./js/jquery-3.3.1.slim.min.js"></script>
    <script src="./js/bootstrap.min.js"></script>
    <script src="./js/RTCMultiConnection.js"></script>
    <script src="./js/socket.io.js"></script>
    <script src="./js/getHTMLMediaElement.js"></script>
    <script src="./js/brodcast-video.js"></script>

    <footer>
        <small id="send-message"></small>
    </footer>

    <script src="./js/common.js"></script>
</body>

</html>